version: "3"

networks:
  catamongo.net:
    driver: bridge

services:
  php:
    build: 
      context: ./
    image: canals/php:8.0
    command: php -S 0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/
    working_dir: /var/www/public
    networks:
      - catamongo.net

  ################################################
  # mongodb & mongo-express
  ###############################################
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
    - ./data:/var/data
    working_dir: /var/data
    networks:
    - catamongo.net
    environment:
      - MONGO_INITDB_DATABASE=firstmongodb
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=rootpassword
    ports:
    - 27017:27017